theme: jekyll-theme-cayman

minima:
  date_format: "%d%M%Y"

title: [ViReR.NeT]
description: [..::ViReR.NeT::.. a random ./linux/sysadmin website]

navbar:
    right:
      - icon: github
        href: https://github.com/virer
        rel: me
      - icon: mastodon
        href: https://fosstodon.org/@virer_dot_net
        rel: me
